<a href="https://colab.research.google.com/github/edgi-govdata-archiving/EEW-ICE/blob/main/ICE_GOV_facs_EJSCREEN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install ECHO_modules

Collecting ECHO_modules
  Downloading echo_modules-0.2.1-py2.py3-none-any.whl.metadata (17 kB)
Collecting delta-spark==3.3.0 (from ECHO_modules)
  Downloading delta_spark-3.3.0-py3-none-any.whl.metadata (2.0 kB)
Collecting deltalake==0.16.4 (from ECHO_modules)
  Downloading deltalake-0.16.4-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: folium>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from ECHO_modules) (0.20.0)
Requirement already satisfied: geopandas>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from ECHO_modules) (1.1.3)
Collecting ipyleaflet==0.19.2 (from ECHO_modules)
  Downloading ipyleaflet-0.19.2-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: ipython>=7.29.0 in /usr/local/lib/python3.12/dist-packages (from ECHO_modules) (7.34.0)
Requirement already satisfied: ipywidgets>=7.6.5 in /usr/local/lib/python3.12/dist-packages (from ECHO_modules) (7.7.1)
Requirement already satisfied: matplotlib>=3.4.3 in /usr/local/lib/python3.12/dist-packages (from ECHO_modules) (3.10.0)
Requirement already satisfied: numpy==2.0.2 in /usr/local/lib/python3.12/dist-packages (from ECHO_modules) (2.0.2)
Requirement already satisfied: pandas>=1.3.4 in /usr/local/lib/python3.12/dist-packages (from ECHO_modules) (2.2.2)
Requirement already satisfied: pyspark>=3.5.4 in /usr/local/lib/python3.12/dist-packages (from ECHO_modules) (4.0.2)
Requirement already satisfied: requests>=2.31.0 in /usr/local/lib/python3.12/dist-packages (from ECHO_modules) (2.32.4)
Requirement already satisfied: seaborn>=0.11.2 in /usr/local/lib/python3.12/dist-packages (from ECHO_modules) (0.13.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ECHO_modules) (4.67.3)
Collecting pyspark>=3.5.4 (from ECHO_modules)
  Downloading pyspark-3.5.8.tar.gz (317.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.8/317.8 MB 4.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: importlib-metadata>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from delta-spark==3.3.0->ECHO_modules) (8.7.1)
Requirement already satisfied: pyarrow>=8 in /usr/local/lib/python3.12/dist-packages (from deltalake==0.16.4->ECHO_modules) (18.1.0)
Collecting pyarrow-hotfix (from deltalake==0.16.4->ECHO_modules)
  Downloading pyarrow_hotfix-0.7-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: branca>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from ipyleaflet==0.19.2->ECHO_modules) (0.8.2)
Collecting jupyter-leaflet<0.20,>=0.19 (from ipyleaflet==0.19.2->ECHO_modules)
  Downloading jupyter_leaflet-0.19.2-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: traittypes<3,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from ipyleaflet==0.19.2->ECHO_modules) (0.2.3)
Requirement already satisfied: xyzservices>=2021.8.1 in /usr/local/lib/python3.12/dist-packages (from ipyleaflet==0.19.2->ECHO_modules) (2026.3.0)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.12/dist-packages (from folium>=0.14.0->ECHO_modules) (3.1.6)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.12/dist-packages (from geopandas>=0.9.0->ECHO_modules) (0.12.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from geopandas>=0.9.0->ECHO_modules) (26.2)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from geopandas>=0.9.0->ECHO_modules) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from geopandas>=0.9.0->ECHO_modules) (2.1.2)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.29.0->ECHO_modules) (75.2.0)
Collecting jedi>=0.16 (from ipython>=7.29.0->ECHO_modules)
  Downloading jedi-0.20.0-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython>=7.29.0->ECHO_modules) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython>=7.29.0->ECHO_modules) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.29.0->ECHO_modules) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.29.0->ECHO_modules) (3.0.52)
Requirement already satisfied: pygments in /usr/local/lib/python3.12/dist-packages (from ipython>=7.29.0->ECHO_modules) (2.20.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython>=7.29.0->ECHO_modules) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython>=7.29.0->ECHO_modules) (0.2.2)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython>=7.29.0->ECHO_modules) (4.9.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.6.5->ECHO_modules) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.6.5->ECHO_modules) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.6.5->ECHO_modules) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ipywidgets>=7.6.5->ECHO_modules) (3.0.16)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.3->ECHO_modules) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.3->ECHO_modules) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.3->ECHO_modules) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.3->ECHO_modules) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.3->ECHO_modules) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.3->ECHO_modules) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.4.3->ECHO_modules) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.4->ECHO_modules) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.4->ECHO_modules) (2026.2)
Requirement already satisfied: py4j<0.10.9.10,>=0.10.9.7 in /usr/local/lib/python3.12/dist-packages (from pyspark>=3.5.4->ECHO_modules) (0.10.9.9)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->ECHO_modules) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->ECHO_modules) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->ECHO_modules) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31.0->ECHO_modules) (2026.5.20)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata>=1.0.0->delta-spark==3.3.0->ECHO_modules) (4.1.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->ECHO_modules) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->ECHO_modules) (7.4.9)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->ECHO_modules) (1.6.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->ECHO_modules) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->ECHO_modules) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.12/dist-packages (from ipykernel>=4.5.1->ipywidgets>=7.6.5->ECHO_modules) (6.5.1)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython>=7.29.0->ECHO_modules) (0.8.7)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2>=2.9->folium>=0.14.0->ECHO_modules) (3.0.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython>=7.29.0->ECHO_modules) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.29.0->ECHO_modules) (0.7.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.4.3->ECHO_modules) (1.17.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.12/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (6.5.7)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets>=7.6.5->ECHO_modules) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.12/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets>=7.6.5->ECHO_modules) (5.9.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (25.1.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (7.17.1)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (0.25.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.12/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (1.3.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from jupyter-core>=4.9.2->jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets>=7.6.5->ECHO_modules) (4.9.6)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.12/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (6.3.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (3.2.1)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.12/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (4.26.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.12/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (25.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.12/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (1.4.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (0.30.0)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.12/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (2.14.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (2.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (4.15.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (3.0)
Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (4.13.0)
Requirement already satisfied: jupyter-events>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (0.5.4)
Requirement already satisfied: overrides>=5.0 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (7.7.0)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.12/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (1.9.0)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (6.0.3)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (0.1.1)
Requirement already satisfied: fqdn in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (1.5.1)
Requirement already satisfied: isoduration in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (1.1.0)
Requirement already satisfied: uri-template in /usr/local/lib/python3.12/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.9.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets>=7.6.5->ECHO_modules) (1.3.0)

In [ ]:
import pandas

facs = pandas.read_csv("ice.csv", dtype={"FAC_LAT": float, "FAC_LONG": float})

facs = facs[["fac", "FAC_LAT", "FAC_LONG"]]

In [ ]:
facs = facs[~facs["FAC_LAT"].isna()]
facs

                                                   fac    FAC_LAT    FAC_LONG
0    Plymouth County Correctional FacilityBoston Fi...  41.932742  -70.657852
1    Wyatt Detention FacilityBoston Field Office950...  41.892811  -71.383200
2    Federal Correctional Institution - Berlin, NH ...  44.523499  -71.136130
3    Strafford County CorrectionsBoston Field Offic...  43.219230  -70.938608
4    Cumberland County JailBoston Field Office50 Co...  43.652372  -70.281138
..                                                 ...        ...         ...
136  Federal Detention Center, Honolulu (FDC Honolu...  21.333362 -157.928350
137  Guam Department of Corrections, Hagatna Detent...  13.475991  144.750484
138  CNMI Department of CorrectionsSan Francisco Fi...  15.158014  145.707280
139  Northwest ICE Processing Center (NWIPC)Seattle...  47.249412 -122.421140
140  Anchorage Correctional ComplexSeattle Field Of...  61.218380 -149.857650

[141 rows x 3 columns]

In [ ]:
from ECHO_modules.get_data import get_ejscreen

data = get_ejscreen(regions=facs, region_type="sites", buffer=3)

data

,EJAM Report,EJSCREEN Map,ejam_uniq_id,valid,invalid_msg,pop,lon,lat,ST,statename,...,state.EJ.DISPARITY.rsei.supp,state.EJ.DISPARITY.traffic.score.supp,state.EJ.DISPARITY.pctpre1960.supp,state.EJ.DISPARITY.proximity.npl.supp,state.EJ.DISPARITY.proximity.rmp.supp,state.EJ.DISPARITY.proximity.tsdf.supp,state.EJ.DISPARITY.ust.supp,state.EJ.DISPARITY.proximity.npdes.supp,state.EJ.DISPARITY.drinking.supp,area_sqmi
0,"<a href=""https://ejamapi-84652557241.us-centra...","<a href=""https://pedp-ejscreen.azurewebsites.n...",1,True,,21467.0,-70.6579,41.9327,MA,Massachusetts,...,32.6019,26.7043,54.4108,0.0000,49.6979,27.3565,65.9044,131.0305,0.0000,28.2743
1,"<a href=""https://ejamapi-84652557241.us-centra...","<a href=""https://pedp-ejscreen.azurewebsites.n...",2,True,,138400.9,-71.3832,41.8928,RI,Rhode Island,...,149.0371,132.7745,107.4991,115.9467,115.7039,136.7872,105.0052,166.8358,5.9266,28.2743
2,"<a href=""https://ejamapi-84652557241.us-centra...","<a href=""https://pedp-ejscreen.azurewebsites.n...",3,True,,2728.8,-71.1361,44.5235,NH,New Hampshire,...,26.8565,46.0002,162.1682,215.3662,176.3803,0.0000,43.5583,49.0001,0.0000,28.2743
3,"<a href=""https://ejamapi-84652557241.us-centra...","<a href=""https://pedp-ejscreen.azurewebsites.n...",4,True,,14780.7,-70.9386,43.2192,NH,New Hampshire,...,65.7699,75.1610,37.0800,114.2082,2.5328,71.2147,68.8575,112.2558,1.3730,28.2743
4,"<a href=""https://ejamapi-84652557241.us-centra...","<a href=""https://pedp-ejscreen.azurewebsites.n...",5,True,,80414.1,-70.2811,43.6524,ME,Maine,...,98.6935,150.9374,124.9873,9.7593,148.1397,150.4525,134.7120,66.5895,133.2571,28.2743
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,"<a href=""https://ejamapi-84652557241.us-centra...","<a href=""https://pedp-ejscreen.azurewebsites.n...",137,True,,77681.1,-157.9283,21.3334,HI,Hawaii,...,103.3099,82.3973,57.8093,103.2156,0.0000,99.3809,66.4470,75.0492,0.0000,28.2743
137,"<a href=""https://ejanalysis.com"", target=""_bla...","<a href=""https://pedp-ejscreen.azurewebsites.n...",138,False,no block centroids (area too small for low pop...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
138,"<a href=""https://ejanalysis.com"", target=""_bla...","<a href=""https://pedp-ejscreen.azurewebsites.n...",139,False,no block centroids (area too small for low pop...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
139,"<a href=""https://ejamapi-84652557241.us-centra...","<a href=""https://pedp-ejscreen.azurewebsites.n...",140,True,,81784.2,-122.4211,47.2494,WA,Washington,...,113.6214,154.6307,143.4536,162.6340,153.5054,149.3137,125.2454,70.9398,0.0000,28.2743
140,"<a href=""https://ejamapi-84652557241.us-centra...","<a href=""https://pedp-ejscreen.azurewebsites.n...",141,True,,73893.1,-149.8577,61.2184,AK,Alaska,...,139.1637,175.8813,122.1733,164.3291,133.1946,165.6151,156.1840,NaN,99.2471,28.2743

In [ ]:
data.to_csv("ice_ejscreen.csv")

In [ ]:
data.columns.to_list()

['EJAM Report',
 'EJSCREEN Map',
 'ejam_uniq_id',
 'valid',
 'invalid_msg',
 'pop',
 'lon',
 'lat',
 'ST',
 'statename',
 'in_how_many_states',
 'REGION',
 'ratio.to.avg.Demog.Index',
 'ratio.to.avg.Demog.Index.Supp',
 'ratio.to.avg.pctlowinc',
 'ratio.to.avg.pctlingiso',
 'ratio.to.avg.pctunemployed',
 'ratio.to.avg.pctlths',
 'ratio.to.avg.pctunder5',
 'ratio.to.avg.pctover64',
 'ratio.to.avg.pctmin',
 'ratio.to.avg.pcthisp',
 'ratio.to.avg.pctnhba',
 'ratio.to.avg.pctnhaa',
 'ratio.to.avg.pctnhaiana',
 'ratio.to.avg.pctnhnhpia',
 'ratio.to.avg.pctnhotheralone',
 'ratio.to.avg.pctnhmulti',
 'ratio.to.avg.pctnhwa',
 'ratio.to.avg.pm',
 'ratio.to.avg.o3',
 'ratio.to.avg.no2',
 'ratio.to.avg.dpm',
 'ratio.to.avg.rsei',
 'ratio.to.avg.traffic.score',
 'ratio.to.avg.pctpre1960',
 'ratio.to.avg.proximity.npl',
 'ratio.to.avg.proximity.rmp',
 'ratio.to.avg.proximity.tsdf',
 'ratio.to.avg.ust',
 'ratio.to.avg.proximity.npdes',
 'ratio.to.avg.drinking',
 'ratio.to.avg.pctdisability',
 'ratio.to.avg.lowlifex',
 'ratio.to.state.avg.Demog.Index',
 'ratio.to.state.avg.Demog.Index.Supp',
 'ratio.to.state.avg.pctlowinc',
 'ratio.to.state.avg.pctlingiso',
 'ratio.to.state.avg.pctunemployed',
 'ratio.to.state.avg.pctlths',
 'ratio.to.state.avg.pctunder5',
 'ratio.to.state.avg.pctover64',
 'ratio.to.state.avg.pctmin',
 'ratio.to.state.avg.pcthisp',
 'ratio.to.state.avg.pctnhba',
 'ratio.to.state.avg.pctnhaa',
 'ratio.to.state.avg.pctnhaiana',
 'ratio.to.state.avg.pctnhnhpia',
 'ratio.to.state.avg.pctnhotheralone',
 'ratio.to.state.avg.pctnhmulti',
 'ratio.to.state.avg.pctnhwa',
 'ratio.to.state.avg.pm',
 'ratio.to.state.avg.o3',
 'ratio.to.state.avg.no2',
 'ratio.to.state.avg.dpm',
 'ratio.to.state.avg.rsei',
 'ratio.to.state.avg.traffic.score',
 'ratio.to.state.avg.pctpre1960',
 'ratio.to.state.avg.proximity.npl',
 'ratio.to.state.avg.proximity.rmp',
 'ratio.to.state.avg.proximity.tsdf',
 'ratio.to.state.avg.ust',
 'ratio.to.state.avg.proximity.npdes',
 'ratio.to.state.avg.drinking',
 'ratio.to.state.avg.pctdisability',
 'ratio.to.state.avg.lowlifex',
 'Demog.Index',
 'Demog.Index.Supp',
 'pctlowinc',
 'pctlingiso',
 'pctunemployed',
 'pctlths',
 'pctunder5',
 'pctover64',
 'pctmin',
 'pcthisp',
 'pctnhba',
 'pctnhaa',
 'pctnhaiana',
 'pctnhnhpia',
 'pctnhotheralone',
 'pctnhmulti',
 'pctnhwa',
 'Demog.Index.State',
 'Demog.Index.Supp.State',
 'pctpoor',
 'occupiedunits',
 'pctmale',
 'pctfemale',
 'lifexyears',
 'percapincome',
 'pctownedunits',
 'pctunder18',
 'pctover17',
 'pctlan_nonenglish',
 'pctlan_ie',
 'pctlan_api',
 'pctlan_other',
 'pctlan_english',
 'pctlan_spanish',
 'pctlan_french',
 'pctlan_rus_pol_slav',
 'pctlan_other_ie',
 'pctlan_vietnamese',
 'pctlan_other_asian',
 'pctlan_arabic',
 'pctspanish_li',
 'pctie_li',
 'pctapi_li',
 'pctother_li',
 'pctdisability',
 'lowlifex',
 'rateheartdisease',
 'rateasthma',
 'ratecancer',
 'yesno_houseburden',
 'yesno_fooddesert',
 'pctnobroadband',
 'pctnohealthinsurance',
 'yesno_transdis',
 'pctfire30',
 'pctflood30',
 'pm',
 'o3',
 'no2',
 'dpm',
 'rsei',
 'traffic.score',
 'pctpre1960',
 'proximity.npl',
 'proximity.rmp',
 'proximity.tsdf',
 'ust',
 'proximity.npdes',
 'drinking',
 'num_school',
 'num_church',
 'num_hospital',
 'yesno_tribal',
 'yesno_impwaters',
 'yesno_airnonatt',
 'yesno_cejstdis',
 'yesno_iradis',
 'count.NPL',
 'count.TSDF',
 'num_airpoll',
 'num_tri',
 'num_waterdis',
 'num_brownfield',
 'sitecount_max',
 'sitecount_unique',
 'sitecount_avg',
 'distance_min',
 'distance_min_avgperson',
 'pctile.Demog.Index',
 'pctile.Demog.Index.Supp',
 'pctile.pctlowinc',
 'pctile.pctlingiso',
 'pctile.pctunemployed',
 'pctile.pctlths',
 'pctile.pctunder5',
 'pctile.pctover64',
 'pctile.pctmin',
 'pctile.pcthisp',
 'pctile.pctnhba',
 'pctile.pctnhaa',
 'pctile.pctnhaiana',
 'pctile.pctnhnhpia',
 'pctile.pctnhotheralone',
 'pctile.pctnhmulti',
 'pctile.pctnhwa',
 'pctile.pctdisability',
 'pctile.lowlifex',
 'pctile.pm',
 'pctile.o3',
 'pctile.no2',
 'pctile.dpm',
 'pctile.rsei',
 'pctile.traffic.score',
 'pctile.pctpre1960',
 'pctile.proximity.npl',
 'pctile.proximity.rmp',
 'pctile.proximity.tsdf',
 'pctile.ust',
 'pctile.proximity.npdes',
 'pctile.drinking',
 'state.pctile.Demog.Index',
 'state.pctile.Demog.Index.Supp',
 'state.pctile.pctlowinc',
 'state.pctile.pctlingiso',
 'state.pctile.pctunemployed',
 'state.pctile.pctlths',
 'state.pctile.pctunder5',
 'state.pctile.pctover64',
 'state.pctile.pctmin',
 'state.pctile.pcthisp',
 'state.pctile.pctnhba',
 'state.pctile.pctnhaa',
 'state.pctile.pctnhaiana',
 'state.pctile.pctnhnhpia',
 'state.pctile.pctnhotheralone',
 'state.pctile.pctnhmulti',
 'state.pctile.pctnhwa',
 'state.pctile.pctdisability',
 'state.pctile.lowlifex',
 'state.pctile.pm',
 'state.pctile.o3',
 'state.pctile.no2',
 'state.pctile.dpm',
 'state.pctile.rsei',
 'state.pctile.traffic.score',
 'state.pctile.pctpre1960',
 'state.pctile.proximity.npl',
 'state.pctile.proximity.rmp',
 'state.pctile.proximity.tsdf',
 'state.pctile.ust',
 'state.pctile.proximity.npdes',
 'state.pctile.drinking',
 'avg.Demog.Index',
 'avg.Demog.Index.Supp',
 'avg.pctlowinc',
 'avg.pctlingiso',
 'avg.pctunemployed',
 'avg.pctlths',
 'avg.pctunder5',
 'avg.pctover64',
 'avg.pctmin',
 'avg.pcthisp',
 'avg.pctnhba',
 'avg.pctnhaa',
 'avg.pctnhaiana',
 'avg.pctnhnhpia',
 'avg.pctnhotheralone',
 'avg.pctnhmulti',
 'avg.pctnhwa',
 'avg.pctdisability',
 'avg.lowlifex',
 'avg.pm',
 'avg.o3',
 'avg.no2',
 'avg.dpm',
 'avg.rsei',
 'avg.traffic.score',
 'avg.pctpre1960',
 'avg.proximity.npl',
 'avg.proximity.rmp',
 'avg.proximity.tsdf',
 'avg.ust',
 'avg.proximity.npdes',
 'avg.drinking',
 'state.avg.Demog.Index',
 'state.avg.Demog.Index.Supp',
 'state.avg.pctlowinc',
 'state.avg.pctlingiso',
 'state.avg.pctunemployed',
 'state.avg.pctlths',
 'state.avg.pctunder5',
 'state.avg.pctover64',
 'state.avg.pctmin',
 'state.avg.pcthisp',
 'state.avg.pctnhba',
 'state.avg.pctnhaa',
 'state.avg.pctnhaiana',
 'state.avg.pctnhnhpia',
 'state.avg.pctnhotheralone',
 'state.avg.pctnhmulti',
 'state.avg.pctnhwa',
 'state.avg.pctdisability',
 'state.avg.lowlifex',
 'state.avg.pm',
 'state.avg.o3',
 'state.avg.no2',
 'state.avg.dpm',
 'state.avg.rsei',
 'state.avg.traffic.score',
 'state.avg.pctpre1960',
 'state.avg.proximity.npl',
 'state.avg.proximity.rmp',
 'state.avg.proximity.tsdf',
 'state.avg.ust',
 'state.avg.proximity.npdes',
 'state.avg.drinking',
 'lowinc',
 'lingiso',
 'unemployed',
 'lths',
 'under5',
 'over64',
 'mins',
 'hisp',
 'nhba',
 'nhaa',
 'nhaiana',
 'nhnhpia',
 'nhotheralone',
 'nhmulti',
 'nhwa',
 'ba',
 'aa',
 'aiana',
 'nhpia',
 'otheralone',
 'multi',
 'wa',
 'age25up',
 'hhlds',
 'unemployedbase',
 'pre1960',
 'builtunits',
 'povknownratio',
 'ownedunits',
 'poor',
 'female',
 'male',
 'over17',
 'under18',
 'lan_nonenglish',
 'lan_ie',
 'lan_api',
 'lan_other',
 'lan_universe',
 'lan_eng_na',
 'lan_spanish',
 'spanish_li',
 'ie_li',
 'api_li',
 'other_li',
 'pctile.EJ.DISPARITY.pm.eo',
 'pctile.EJ.DISPARITY.o3.eo',
 'pctile.EJ.DISPARITY.no2.eo',
 'pctile.EJ.DISPARITY.dpm.eo',
 'pctile.EJ.DISPARITY.rsei.eo',
 'pctile.EJ.DISPARITY.traffic.score.eo',
 'pctile.EJ.DISPARITY.pctpre1960.eo',
 'pctile.EJ.DISPARITY.proximity.npl.eo',
 'pctile.EJ.DISPARITY.proximity.rmp.eo',
 'pctile.EJ.DISPARITY.proximity.tsdf.eo',
 'pctile.EJ.DISPARITY.ust.eo',
 'pctile.EJ.DISPARITY.proximity.npdes.eo',
 'pctile.EJ.DISPARITY.drinking.eo',
 'pctile.EJ.DISPARITY.pm.supp',
 'pctile.EJ.DISPARITY.o3.supp',
 'pctile.EJ.DISPARITY.no2.supp',
 'pctile.EJ.DISPARITY.dpm.supp',
 'pctile.EJ.DISPARITY.rsei.supp',
 'pctile.EJ.DISPARITY.traffic.score.supp',
 'pctile.EJ.DISPARITY.pctpre1960.supp',
 'pctile.EJ.DISPARITY.proximity.npl.supp',
 'pctile.EJ.DISPARITY.proximity.rmp.supp',
 'pctile.EJ.DISPARITY.proximity.tsdf.supp',
 'pctile.EJ.DISPARITY.ust.supp',
 'pctile.EJ.DISPARITY.proximity.npdes.supp',
 'pctile.EJ.DISPARITY.drinking.supp',
 'state.pctile.EJ.DISPARITY.pm.eo',
 'state.pctile.EJ.DISPARITY.o3.eo',
 'state.pctile.EJ.DISPARITY.no2.eo',
 'state.pctile.EJ.DISPARITY.dpm.eo',
 'state.pctile.EJ.DISPARITY.rsei.eo',
 'state.pctile.EJ.DISPARITY.traffic.score.eo',
 'state.pctile.EJ.DISPARITY.pctpre1960.eo',
 'state.pctile.EJ.DISPARITY.proximity.npl.eo',
 'state.pctile.EJ.DISPARITY.proximity.rmp.eo',
 'state.pctile.EJ.DISPARITY.proximity.tsdf.eo',
 'state.pctile.EJ.DISPARITY.ust.eo',
 'state.pctile.EJ.DISPARITY.proximity.npdes.eo',
 'state.pctile.EJ.DISPARITY.drinking.eo',
 'state.pctile.EJ.DISPARITY.pm.supp',
 'state.pctile.EJ.DISPARITY.o3.supp',
 'state.pctile.EJ.DISPARITY.no2.supp',
 'state.pctile.EJ.DISPARITY.dpm.supp',
 'state.pctile.EJ.DISPARITY.rsei.supp',
 'state.pctile.EJ.DISPARITY.traffic.score.supp',
 'state.pctile.EJ.DISPARITY.pctpre1960.supp',
 'state.pctile.EJ.DISPARITY.proximity.npl.supp',
 'state.pctile.EJ.DISPARITY.proximity.rmp.supp',
 'state.pctile.EJ.DISPARITY.proximity.tsdf.supp',
 'state.pctile.EJ.DISPARITY.ust.supp',
 'state.pctile.EJ.DISPARITY.proximity.npdes.supp',
 'state.pctile.EJ.DISPARITY.drinking.supp',
 'bgcount_near_site',
 'blockcount_near_site',
 'radius.miles',
 'disability',
 'disab_universe',
 'areawater',
 'arealand',
 'area',
 'pctba',
 'pctaa',
 'pctaiana',
 'pctnhpia',
 'pctotheralone',
 'pctmulti',
 'pctwa',
 'EJ.DISPARITY.pm.eo',
 'EJ.DISPARITY.o3.eo',
 'EJ.DISPARITY.no2.eo',
 'EJ.DISPARITY.dpm.eo',
 'EJ.DISPARITY.rsei.eo',
 'EJ.DISPARITY.traffic.score.eo',
 'EJ.DISPARITY.pctpre1960.eo',
 'EJ.DISPARITY.proximity.npl.eo',
 'EJ.DISPARITY.proximity.rmp.eo',
 'EJ.DISPARITY.proximity.tsdf.eo',
 'EJ.DISPARITY.ust.eo',
 'EJ.DISPARITY.proximity.npdes.eo',
 'EJ.DISPARITY.drinking.eo',
 'state.EJ.DISPARITY.pm.eo',
 'state.EJ.DISPARITY.o3.eo',
 'state.EJ.DISPARITY.no2.eo',
 'state.EJ.DISPARITY.dpm.eo',
 'state.EJ.DISPARITY.rsei.eo',
 'state.EJ.DISPARITY.traffic.score.eo',
 'state.EJ.DISPARITY.pctpre1960.eo',
 'state.EJ.DISPARITY.proximity.npl.eo',
 'state.EJ.DISPARITY.proximity.rmp.eo',
 'state.EJ.DISPARITY.proximity.tsdf.eo',
 'state.EJ.DISPARITY.ust.eo',
 'state.EJ.DISPARITY.proximity.npdes.eo',
 'state.EJ.DISPARITY.drinking.eo',
 'EJ.DISPARITY.pm.supp',
 'EJ.DISPARITY.o3.supp',
 'EJ.DISPARITY.no2.supp',
 'EJ.DISPARITY.dpm.supp',
 'EJ.DISPARITY.rsei.supp',
 'EJ.DISPARITY.traffic.score.supp',
 'EJ.DISPARITY.pctpre1960.supp',
 'EJ.DISPARITY.proximity.npl.supp',
 'EJ.DISPARITY.proximity.rmp.supp',
 'EJ.DISPARITY.proximity.tsdf.supp',
 'EJ.DISPARITY.ust.supp',
 'EJ.DISPARITY.proximity.npdes.supp',
 'EJ.DISPARITY.drinking.supp',
 'state.EJ.DISPARITY.pm.supp',
 'state.EJ.DISPARITY.o3.supp',
 'state.EJ.DISPARITY.no2.supp',
 'state.EJ.DISPARITY.dpm.supp',
 'state.EJ.DISPARITY.rsei.supp',
 'state.EJ.DISPARITY.traffic.score.supp',
 'state.EJ.DISPARITY.pctpre1960.supp',
 'state.EJ.DISPARITY.proximity.npl.supp',
 'state.EJ.DISPARITY.proximity.rmp.supp',
 'state.EJ.DISPARITY.proximity.tsdf.supp',
 'state.EJ.DISPARITY.ust.supp',
 'state.EJ.DISPARITY.proximity.npdes.supp',
 'state.EJ.DISPARITY.drinking.supp',
 'area_sqmi']